- id: doi:10.1111/2041-210X.14225
  type: paper
  description: EMLN package and guidelines
  image: https://besjournals.onlinelibrary.wiley.com/cms/asset/d12add0e-b1fd-4727-9d4d-affcbc5e65c8/mee314225-fig-0001-m.jpg
  buttons:
    - type: website
      link: https://ecological-complexity-lab.github.io/emln_package/
  tags:
    - R
    - package
  repo: https://github.com/Ecological-Complexity-Lab/emln_package
