- id: doi:10.1111/2041-210X.14225
  type: paper
  description: EMLN package and guidelines
  image: images/projects/emln_pic.jpg # https://besjournals.onlinelibrary.wiley.com/cms/asset/d12add0e-b1fd-4727-9d4d-affcbc5e65c8/mee314225-fig-0001-m.jpg
  buttons:
    - type: website
      link: https://ecological-complexity-lab.github.io/emln_package/
  tags:
    - R
    - package
  repo: https://github.com/Ecological-Complexity-Lab/emln_package
  
- id: doi:10.32942/X28G7K
  image: images/publications/pic_local_and_regional_processes.png
  
- id: doi:10.32942/X2161C
  image: images/publications/pic_scale_dependent_signatures.png
  
- id: doi:10.1038/s41467-023-41906-2
  type: paper
  image: https://www.nature.com/articles/s41467-023-41906-2/figures/1
  
- id: doi:10.1016/j.tim.2023.01.007
  type: paper
  image: images/publications/pic_conceptualizing_microbeplasmid_1.png
  
- id: doi:10.1098/rspb.2023.0132
  type: paper
  image: https://royalsocietypublishing.org/doi/10.1098/rspb.2023.0132
