- id: doi:10.1111/2041-210X.14225
  type: paper
  description: EMLN package and guidelines
  image: images/projects/emln_pic.jpg #https://besjournals.onlinelibrary.wiley.com/cms/asset/d12add0e-b1fd-4727-9d4d-affcbc5e65c8/mee314225-fig-0001-m.jpg  
  buttons:
    - type: website
      link: https://ecological-complexity-lab.github.io/emln_package/
  tags:
    - R
    - package
  repo: https://github.com/Ecological-Complexity-Lab/emln_package
  
- id: doi:10.32942/X28G7K
  image: images/publications/pic_local_and_regional_processes.png
  
- id: doi:10.32942/X2161C
  image: images/publications/pic_scale_dependent_signatures.png
  
- id: doi:10.1038/s41467-023-41906-2
  type: paper
  image: images/publications/pic_ecological_network_analysis_reveals_cancer.png # https://www.nature.com/articles/s41467-023-41906-2/figures/1
  
- id: doi:10.1016/j.tim.2023.01.007
  type: paper
  image: images/publications/pic_conceptualizing_microbeplasmid_1.png
  
- id: doi:10.1098/rspb.2023.0132
  type: paper
  image: images/publications/pic_invasive_species_modulate_the_structure.jpeg # https://royalsocietypublishing.org/doi/10.1098/rspb.2023.0132

- id: doi:10.1038/s41396-023-01373-5
  type: paper
  image: images/publications/pic_multilayer_networks_of_plasmid_genetics.png

- id: doi:10.1371/journal.pcbi.1009319
  type: paper
  image: images/publications/pic_the_inerplay_between_vaccination_and_COVID19.jpeg

- id: doi:10.3389/fevo.2021.633263
  type: paper
  image: https://www.frontiersin.org/files/Articles/633263/fevo-09-633263-HTML-r2/image_m/fevo-09-633263-g001.jpg #images/publications/pic_frequency_dependent_competition_between_strains.jpeg

- id: doi:10.1111/2041-210X.13569
  type: paper
  image: images/publications/pic_identifying_flow_modules_in_ec_net_infomap.jpeg

- id: doi:10.1038/s41559-020-01312-z
  type: paper
  image: images/publications/pic_the_network_structure_and_eco_evol_CRISPR.webp
  
- id: doi:10.3390/cancers12040825
  type: paper
  image: images/publications/pic_pan_cancer_analysis_of_mitochondria_chaperone.png

- id: doi:10.1371/journal.pbio.3000336
  type: paper
  image: images/publications/pic_comp_for_hosts_in_Plasmodium_falciparum.jpeg

- id: doi:10.1038/s41467-018-04219-3
  type: paper
  image: images/publications/pic_net_of_genetics_similaruty_Plasmodium_falciparum.webp

- id: doi:10.1016/j.jtbi.2017.07.020
  type: paper
  image: images/publications/pic_asymmetric_disease_dynamics.jpeg

- id: doi:10.1038/s41559-017-0101
  type: paper
  image: images/publications/pic_the_multilayer_nature_of_ecological_net.webp

- id: doi:10.1890/13-0678.1
  type: paper
  image: https://esajournals.onlinelibrary.wiley.com/cms/asset/fef9467a-1eba-4403-ba9b-9a83f870ae05/ecy20149551173-fig-0001-m.jpg

- id: doi:10.1016/j.mambio.2013.10.005
  type: paper
  image: images/publications/pic_effects_of_sewage_water_desert_bat.jpg

- id: doi:10.1111/1365-2656.12134
  type: paper
  image: images/publications/pic_tradeoff_between_quantity_and_quality.jpg

- id: doi:10.1017/s0031182013001376
  type: paper
  image: images/publications/pic_phylogenrtic_structure_of_host_spectra_in_palaearctic_fleas.jpg

- id: doi:10.1016/j.ijpara.2013.05.001
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0020751913001434-fx1_lrg.jpg

- id: doi:10.1111/1365-2656.12101
  type: paper
  image: images/publications/pic_phylogeny_determines_the_role_food_webs.jpg

- id: doi:10.1111/j.1600-0706.2013.00646.x
  type: paper
  image: images/publications/pic_coocurrence_and_phylogenetic_distance.jpg

- id: doi:10.1080/15659801.2013.865338
  type: paper
  image: images/publications/pic_evolution_of_culture.jpg

- id: doi:10.1111/1365-2656.12090
  type: paper
  image: images/publications/pic_temporal_dynamics_host_parasite_network.jpg

- id: doi:10.1017/s0031182012001205
  type: paper
  image: images/publications/pic_phylogenrtic_structure_of_host_spectra_in_palaearctic_fleas.jpg

- id: doi:10.1371/journal.pone.0041487
  type: paper
  image: images/publications/pic_effects_of_anthropogenic_disturbance.jpeg

- id: doi:10.1644/09-mamm-a-370.1
  type: paper
  image: images/publications/pic_variability_in_urine_concentration.jpg
